<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsTableSeeder extends Seeder
{
    protected $depends = [
        CompaniesTableSeeder::class,
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        if ($this->hasAlreadyRun('projects')) {
            $this->command->info('Skipping ProjectsTableSeeder as it has already run.');
            return;
        }

        $this->callDependencies();

        $projects = [
            [
                'id' => 1,
                'created_at' => '2023-05-23 23:23:31',
                'updated_at' => '2023-07-01 07:54:29',
                'name' => 'Project #1',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 30000000,
                'current_capital' => 24254000,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 1,
                'profit_margin_bersama' => 60,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 2,
                'created_at' => '2023-05-23 23:23:50',
                'updated_at' => '2023-05-23 23:23:50',
                'name' => 'Project #2',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 30000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 1,
                'profit_margin_bersama' => 60,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 3,
                'created_at' => '2023-05-23 23:23:57',
                'updated_at' => '2023-05-23 23:23:57',
                'name' => 'Project #3',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 30000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 1,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 4,
                'created_at' => '2023-05-23 23:24:06',
                'updated_at' => '2023-05-23 23:24:06',
                'name' => 'Project #4',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 30000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 2,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 5,
                'created_at' => '2023-05-23 23:24:18',
                'updated_at' => '2023-05-23 23:24:18',
                'name' => 'Project #5',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 30000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 2,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 6,
                'created_at' => '2023-05-23 23:24:34',
                'updated_at' => '2023-05-23 23:24:34',
                'name' => 'Project #6',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 40000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 3,
                'profit_margin_bersama' => 60,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 7,
                'created_at' => '2023-05-23 23:24:43',
                'updated_at' => '2023-05-23 23:24:43',
                'name' => 'Project #7',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 40000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 3,
                'profit_margin_bersama' => 60,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 8,
                'created_at' => '2023-05-23 23:24:50',
                'updated_at' => '2023-05-23 23:24:50',
                'name' => 'Project #8',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 40000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 3,
                'profit_margin_bersama' => 60,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 9,
                'created_at' => '2023-05-23 23:24:59',
                'updated_at' => '2023-05-23 23:24:59',
                'name' => 'Project #9',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 50000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 4,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 10,
                'created_at' => '2023-05-23 23:25:09',
                'updated_at' => '2023-05-23 23:25:09',
                'name' => 'Project #10',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 50000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 4,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 11,
                'created_at' => '2023-05-23 23:25:19',
                'updated_at' => '2023-05-23 23:25:19',
                'name' => 'Project #11',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 50000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 4,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 12,
                'created_at' => '2023-05-23 23:25:31',
                'updated_at' => '2023-05-23 23:25:31',
                'name' => 'Project #12',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 60000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 5,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 13,
                'created_at' => '2023-05-23 23:25:42',
                'updated_at' => '2023-05-23 23:25:42',
                'name' => 'Project #13',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 60000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 5,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 14,
                'created_at' => '2023-05-23 23:25:54',
                'updated_at' => '2023-05-23 23:25:54',
                'name' => 'Project #14',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 70000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 6,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 15,
                'created_at' => '2023-05-23 23:26:03',
                'updated_at' => '2023-05-23 23:26:03',
                'name' => 'Project #15',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 70000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 6,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 16,
                'created_at' => '2023-05-23 23:26:11',
                'updated_at' => '2023-05-23 23:26:11',
                'name' => 'Project #16',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 80000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 7,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 17,
                'created_at' => '2023-05-23 23:26:22',
                'updated_at' => '2023-05-23 23:26:22',
                'name' => 'Project #17',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 80000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 7,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 18,
                'created_at' => '2023-05-23 23:26:31',
                'updated_at' => '2023-05-23 23:26:31',
                'name' => 'Project #18',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 90000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 8,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 19,
                'created_at' => '2023-05-23 23:26:40',
                'updated_at' => '2023-05-23 23:26:40',
                'name' => 'Project #19',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 90000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 8,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 20,
                'created_at' => '2023-05-23 23:26:49',
                'updated_at' => '2023-05-23 23:26:49',
                'name' => 'Project #20',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 100000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 9,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 21,
                'created_at' => '2023-05-23 23:26:59',
                'updated_at' => '2023-05-23 23:26:59',
                'name' => 'Project #21',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 100000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 9,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 22,
                'created_at' => '2023-05-23 23:27:10',
                'updated_at' => '2023-05-23 23:27:10',
                'name' => 'Project #22',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 110000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 10,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 23,
                'created_at' => '2023-05-23 23:27:19',
                'updated_at' => '2023-05-23 23:27:19',
                'name' => 'Project #23',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 110000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 10,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
            [
                'id' => 24,
                'created_at' => '2023-05-23 23:27:28',
                'updated_at' => '2023-05-23 23:27:28',
                'name' => 'Project #24',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at finibus urna. Integer ac felis ullamcorper, tempus massa eu, dapibus velit. Aliquam erat volutpat. Nulla facilisi. Sed dictum libero a arcu cur',
                'required_capital' => 120000000,
                'current_capital' => null,
                'progress_status' => 'aktif',
                'project_photo' => '202305280804Aldika\'s Signature.png',
                'company_id' => 11,
                'profit_margin_bersama' => 40,
                'profit_margin_investor' => 40,
                'profit' => 0,
                'order_id' => null,
            ],
        ];

        DB::table('projects')->insert($projects);
    }

        /**
     * Check if the seeder has already been run.
     *
     * @param  string  $table
     * @return bool
     */
    protected function hasAlreadyRun($table)
    {
        $count = DB::table($table)->count();
        return $count > 0;
    }

    /**
     * Call the seeders that this seeder depends on.
     *
     * @return void
     */
    protected function callDependencies()
    {
        foreach ($this->depends as $seeder) {
            $this->call($seeder);
        }
    }
}
